export const venue = {
  name: "Visvesvaraya Auditorium",
  college: "Impact College of Engineering and Applied Sciences",
  address:
    "Kodigehalli, South, 60 Feet Rd, Sahakar Nagar, Koti Hosahalli, Bengaluru, Karnataka 560092",
  streetAddress: "60 Feet Rd, Sahakar Nagar",
  locality: "Koti Hosahalli, Bengaluru",
  region: "Karnataka",
  postalCode: "560092",
  country: "IN",
  coordinates: { lat: 13.0542017, lng: 77.5814526 },
  mapEmbedUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.123!2d77.5814526!3d13.0542017!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1821856cd1bd%3A0x38b02823deefc8ab!2sImpact+College+of+Engineering+and+Applied+Sciences!5e0!3m2!1sen!2sin",
  fullLocation:
    "Visvesvaraya Auditorium, Impact College of Engineering and Applied Sciences, Kodigehalli, South, 60 Feet Rd, Sahakar Nagar, Koti Hosahalli, Bengaluru, Karnataka 560092",
  shortLocation: "Visvesvaraya Auditorium, Impact College, Bengaluru",
};

export const event = {
  name: "TEDxICEAS 2026 | What shapes us? | Official TEDx Event Bengaluru",
  shortName: "TEDxICEAS 2026",
  description:
    "TEDxICEAS 2026 is an independently organized TEDx event at Visvesvaraya Auditorium, Impact College of Engineering and Applied Sciences, Sahakar Nagar, Bengaluru. Theme: 'What shapes us?'. Book passes to experience live talks from inspiring leaders, tech visionaries, athletes, and innovators.",
  startDate: "2026-08-10T09:00:00+05:30",
  endDate: "2026-08-10T18:00:00+05:30",
  email: "tedxiceas@gmail.com",
  url: "https://tedxiceas.com",
  keywords: [
    "TEDx",
    "TEDxICEAS",
    "TEDx ICEAS",
    "TEDxICEAS 2026",
    "TEDx Bangalore",
    "TEDx Bengaluru",
    "TEDx Karnataka",
    "TEDx India",
    "TEDx Events Bangalore",
    "TEDx Talks 2026",
    "TEDx Speakers 2026",
    "TEDx Speaker Lineup",
    "TEDx Tickets Bangalore",
    "TEDx Pass Booking",
    "What shapes us",
    "Impact College of Engineering and Applied Sciences",
    "ICEAS Bengaluru",
    "Visvesvaraya Auditorium",
    "Sahakar Nagar Bengaluru",
    "Arun Prasanna",
    "Dr Saheer Nelliparamban",
    "Fazlur Rahman Khan",
    "Dr Ghazala Ahmed Shafi",
    "Neole Anna Cornelio",
    "Sanjay R Google",
    "Shweta Vohra Booking.com",
    "Ideas worth spreading",
    "Innovation Conference Bengaluru",
    "Technology Entertainment Design",
  ],
  speakers: [
    {
      name: "Arun Prasanna",
      jobTitle: "Hospitality Business Leader & Entrepreneur",
      description: "Hospitality business leader with over a decade of experience building and scaling premium dining brands.",
      image: "https://tedxiceas.com/speakers/arun-prasanna.jpg",
    },
    {
      name: "Dr. Saheer Nelliparamban",
      jobTitle: "Founder & CEO, Paywint | Forbes Council Member",
      description: "Doctor, entrepreneur, Founder and CEO of Paywint, Fichecks, and Gasdeck, Forbes Business Council Member.",
      image: "https://tedxiceas.com/speakers/dr-saheer-nelliparamban.jpg",
    },
    {
      name: "Fazlur Rahman Khan",
      jobTitle: "Technical Trainer, Linux Foundation | Kubestronaut",
      description: "Technical Trainer at The Linux Foundation, 20+ years in database architecture and cloud-native infrastructure, India's first Kubestronaut.",
      image: "https://tedxiceas.com/speakers/fazlur-rahman-khan.jpg",
    },
    {
      name: "Dr. Ghazala Ahmed Shafi",
      jobTitle: "Chief Dental Surgeon | Laser Specialist of the Year",
      description: "Head and Chief Dental Surgeon at Dr. Ghazala's Dental, MDS in Periodontology, Laser Specialist of the Year 2022.",
      image: "https://tedxiceas.com/speakers/dr-ghazala-ahmed-shafi.jpg",
    },
    {
      name: "Neole Anna Cornelio",
      jobTitle: "International Sprinter | Gold Medalist & Record Holder",
      description: "International sprinter representing India in 4x100m relay, Junior SAAF gold medalist & national record holder.",
      image: "https://tedxiceas.com/speakers/neole-anna-cornelio.jpg",
    },
    {
      name: "Sanjay R",
      jobTitle: "Community Manager, Google for Developers",
      description: "Community builder, entrepreneur, Youngest District Rotaract Representative, Community Manager at Google for Developers.",
      image: "https://tedxiceas.com/speakers/sanjay-r.jpg",
    },
    {
      name: "Shweta Vohra",
      jobTitle: "Architecture Leader, Booking.com | Author & Inventor",
      description: "Technology leader with 24+ years experience, Architecture leader at Booking.com, author of Decoding Platform Engineering Patterns.",
      image: "https://tedxiceas.com/speakers/shweta-vohra.jpg",
    },
  ],
};

