export const venue = {
  name: "Visvesvaraya Auditorium",
  college: "Impact College of Engineering and Applied Sciences",
  address:
    "Kodigehalli, South, 60 Feet Rd, Sahakar Nagar, Koti Hosahalli, Bengaluru, Karnataka 560092",
  streetAddress: "60 Feet Rd, Sahakar Nagar",
  locality: "Koti Hosahalli, Bengaluru",
  region: "Karnataka",
  postalCode: "560092",
  country: "IN",
  coordinates: { lat: 13.0542017, lng: 77.5814526 },
  mapEmbedUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.123!2d77.5814526!3d13.0542017!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1821856cd1bd%3A0x38b02823deefc8ab!2sImpact+College+of+Engineering+and+Applied+Sciences!5e0!3m2!1sen!2sin",
  fullLocation:
    "Visvesvaraya Auditorium, Impact College of Engineering and Applied Sciences, Kodigehalli, South, 60 Feet Rd, Sahakar Nagar, Koti Hosahalli, Bengaluru, Karnataka 560092",
  shortLocation: "Visvesvaraya Auditorium, Impact College, Bengaluru",
};

export const event = {
  name: "TEDxICEAS 2026 | What shapes us? | Official TEDx Event Bengaluru",
  shortName: "TEDxICEAS 2026",
  description:
    "TEDxICEAS 2026 is an independently organized TEDx event at Visvesvaraya Auditorium, Impact College of Engineering and Applied Sciences, Sahakar Nagar, Bengaluru. Theme: 'What shapes us?'. Book passes to experience live talks from inspiring leaders, tech visionaries, athletes, and innovators.",
  startDate: "2026-08-10T09:00:00+05:30",
  endDate: "2026-08-10T18:00:00+05:30",
  email: "tedxiceas@gmail.com",
  url: "https://tedxiceas.in",
  keywords: [
    "TEDx",
    "TEDxICEAS",
    "TEDx ICEAS",
    "TEDxICEAS 2026",
    "TEDx Bangalore",
    "TEDx Bengaluru",
    "TEDx Karnataka",
    "TEDx India",
    "TEDx Events Bangalore",
    "TEDx Talks 2026",
    "TEDx Speakers 2026",
    "TEDx Speaker Lineup",
    "TEDx Tickets Bangalore",
    "TEDx Pass Booking",
    "What shapes us",
    "Impact College of Engineering and Applied Sciences",
    "ICEAS Bengaluru",
    "Visvesvaraya Auditorium",
    "Sahakar Nagar Bengaluru",
    "Huda Thamanna",
    "Huda Thamanna TEDx",
    "Huda Thamanna TEDxICEAS",
    "Arun Prasanna",
    "Arun Prasanna TEDx",
    "Arun Prasanna TEDxICEAS",
    "Dr Saheer Nelliparamban",
    "Dr Saheer Nelliparamban TEDx",
    "Saheer Nelliparamban Paywint",
    "Fazlur Rahman Khan",
    "Fazlur Rahman Khan TEDx",
    "Fazlur Rahman Linux Foundation",
    "Dr Ghazala Ahmed Shafi",
    "Dr Ghazala Ahmed Shafi TEDx",
    "Neole Anna Cornelio",
    "Neole Anna Cornelio TEDx",
    "Neole Anna Cornelio sprinter",
    "Sanjay R Google",
    "Sanjay R TEDx",
    "Shweta Vohra Booking.com",
    "Shweta Vohra TEDx",
    "Dr Lokesh B Aster CMI",
    "Dr Lokesh B TEDx",
    "Manish Kankaria Bombay Kulfi",
    "Manish Kankaria TEDx",
    "Kapil Ahuja Nagarro",
    "Kapil Ahuja TEDx",
    "Ideas worth spreading",
    "Innovation Conference Bengaluru",
    "Technology Entertainment Design",
  ],
  speakers: [
    {
      name: "Huda Thamanna",
      jobTitle: "Content Creator",
      description: "Huda Thamanna is a content creator whose journey is rooted in authenticity, creativity, and connection.",
      image: "https://tedxiceas.in/speakers/huda-thamanna.jpg",
    },
    {
      name: "Arun Prasanna",
      jobTitle: "Hospitality Business Leader & Entrepreneur",
      description: "Hospitality business leader with over a decade of experience building and scaling premium dining brands.",
      image: "https://tedxiceas.in/speakers/arun-prasanna.jpg",
    },
    {
      name: "Dr. Saheer Nelliparamban",
      jobTitle: "Founder & CEO, Paywint | Forbes Council Member",
      description: "Doctor, entrepreneur, Founder and CEO of Paywint, Fichecks, and Gasdeck, Forbes Business Council Member.",
      image: "https://tedxiceas.in/speakers/dr-saheer-nelliparamban.jpg",
    },
    {
      name: "Fazlur Rahman Khan",
      jobTitle: "Technical Trainer, Linux Foundation | Kubestronaut",
      description: "Technical Trainer at The Linux Foundation, 20+ years in database architecture and cloud-native infrastructure, India's first Kubestronaut.",
      image: "https://tedxiceas.in/speakers/fazlur-rahman-khan.jpg",
    },
    {
      name: "Dr. Ghazala Ahmed Shafi",
      jobTitle: "Chief Dental Surgeon | Laser Specialist of the Year",
      description: "Head and Chief Dental Surgeon at Dr. Ghazala's Dental, MDS in Periodontology, Laser Specialist of the Year 2022.",
      image: "https://tedxiceas.in/speakers/dr-ghazala-ahmed-shafi.jpg",
    },
    {
      name: "Neole Anna Cornelio",
      jobTitle: "International Sprinter | Gold Medalist & Record Holder",
      description: "International sprinter representing India in 4x100m relay, Junior SAAF gold medalist & national record holder.",
      image: "https://tedxiceas.in/speakers/neole-anna-cornelio.jpg",
    },
    {
      name: "Sanjay R",
      jobTitle: "Community Manager | District Rotaract Representative | RI District 3192",
      description: "Community builder, entrepreneur, Youngest District Rotaract Representative, Community Manager at Google for Developers.",
      image: "https://tedxiceas.in/speakers/sanjay-r.jpg",
    },
    {
      name: "Shweta Vohra",
      jobTitle: "Architecture Leader, Booking.com | Author & Inventor",
      description: "Technology leader with 24+ years experience, Architecture leader at Booking.com, author of Decoding Platform Engineering Patterns.",
      image: "https://tedxiceas.in/speakers/shweta-vohra.jpg",
    },
    {
      name: "Dr. Lokesh B",
      jobTitle: "Senior Consultant in Neurology, Aster CMI Hospital",
      description: "Senior Consultant in Neurology at Aster CMI Hospital, Bangalore with MBBS, MD, and DM in Neurology.",
      image: "https://tedxiceas.in/speakers/dr-lokesh-b.jpg",
    },
    {
      name: "Manish Kankaria",
      jobTitle: "Founder, Bombay Kulfi | Entrepreneur & CA",
      description: "Founder of Bombay Kulfi Ice Creams, 100+ outlets across India & Singapore, Chartered Accountant.",
      image: "https://tedxiceas.in/speakers/manish-kankaria.jpg",
    },
    {
      name: "Kapil Ahuja",
      jobTitle: "CTO of Ventures & Studios, Nagarro | Author & Architect",
      description: "CTO of Ventures and Studios at Nagarro, writer at HowToArchitect.io, systems architect & technology leader.",
      image: "https://tedxiceas.in/speakers/kapil-ahuja.jpg",
    },
  ],
};

